apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warehouse-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: warehouse-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/prod/warehouse-microservice
        property: DATABASE_URL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/warehouse-microservice
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/prod/warehouse-microservice
        property: JWT_SECRET
